# **🚀 Базовая линейная алгебра в Julia**  
# **Урок Двенадцатый.**

**Автор**: Андреас Ноак Йенсен (MIT & JuliaComputing) [(Twitter)](https://x.com/anoackjensen)  
(с правками от Джейн Херриман и Сергея Соболевского)

<br>

##  **📌 Темы:**  

1. **Основные понятия линейной алгебры**
2. **Создание матрицы и вектора в Julia.**  
3. **Стандартные матричные операции в Julia.**
4. **Решение линейных систем (Solving Linear Systems).** 
5. **Библиотека `LinearAlgebra`.**



<br>

---

 <br>


## 🎯 После этого занятия вы сможете

- создавать векторы и матрицы и уверенно читать их типы (`Vector`, `Matrix`, `Adjoint`);
- пользоваться `size`, `length` и понимать, чем `Vector` отличается от матрицы-столбца;
- применять `transpose` и `'` осознанно, зная, когда они расходятся;
- вычислять `dot`, `cross`, `norm`, `det`, `rank`, `tr`;
- решать системы `A \ b` — квадратные, переопределённые и недоопределённые;
- пользоваться типами структуры (`Diagonal`, `Symmetric`, `UpperTriangular`)
  и понимать, что это **обещание**, а не проверка;
- объяснять, почему за операциями Julia стоит BLAS/LAPACK.

### Связь с предыдущим занятием

В **занятии 11** мы разобрали, *что означают* эти операции математически.
Здесь мы систематически осваиваем **инструмент** — библиотеку `LinearAlgebra`.
Если какая-то формула кажется незнакомой, вернитесь к занятию 11.

# **Базовая линейная алгебра в Julia.**

**Линейная алгебра** — это раздел математики, изучающий векторы, матрицы, линейные уравнения и линейные преобразования. Она является основой для многих областей, включая компьютерные науки, машинное обучение, обработку сигналов и физику.

<br>

В **Julia** для вычисления определителя матриц больших размерностей ($ n>3 $) используется функция `LinearAlgebra.det` из стандартной библиотеки `LinearAlgebra`,
**Julia** использует LU-разложение (аналогично методу Гаусса), что обеспечивает высокую эффективность даже для очень больших матриц ($n≥1000$). Для работы с символьными матрицами в Julia
можно подключить пакет `Symbolics.jl`, для численных вычислений используется тип данных матрицы (например, `Float64` или `BigFloat` для повышенной точности).

<br>

---

<br>

### **1️⃣ Создание матрицы и вектора в Julia.**  

В Julia векторы и матрицы представляют собой массивы `(Array)`, но они имеют разную размерность. 

**Вектор** — это одномерный массив, а **Матрица** — двумерный.

#### **🔹 Определение заданной матрицы** 

Сначала создадим простую иатрицу А размером 3х3:

```julia
A = [1 2 3; 
     4 5 6; 
     7 8 9]  # Задаем матрицу A (3×3)
```

In [1]:
A = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9


#### **🔹 Определение случайной матрицы**  

Теперь создадим **случайную матрицу** `A` размером **3×3**, содержащую целые числа от 1 до 10:  


In [2]:
A = rand(1:10, 3, 3) # Определяем матрицу 3x3, заполненную случайными числами от 1 до 10


3×3 Matrix{Int64}:
 3  8  1
 2  6  8
 3  7  4

#### **🔹 Определение вектора из единиц.** 
 
Теперь создадим **вектор**, содержащий только целые числа - единицы `1`, размером **3 элемента**:  

In [3]:
x = fill(1,3)  # Определяем вектор x = [1, 1, 1]

3-element Vector{Int64}:
 1
 1
 1

#### **🔹 Определение вектора случайных чисел.** 

С помощью функциии `rand()` определяем вектор `b`, заполненный случайными числами от 1 до 10 и размерностью 5 элементов:

In [4]:
b = rand(1:10, 5)    # Определяем вектор b длины 5, заполненный случайными числами от 1 до 10

5-element Vector{Int64}:
 3
 9
 7
 2
 8

#### **🔹 Определение вектора случайных чисел от 0 до 1.**

Функция `rand(n)` в Julia по умолчанию генерирует **n** случайных чисел из равномерного распределения на интервале **[0, 1]**.

In [5]:
z = rand(3) # вектор x длины 3, заполненный случайными числами от 0 до 1

3-element Vector{Float64}:
 0.16077468125363414
 0.515281585605481
 0.3684878402810058

#### **🔹 Функция collect() в Julia.**

Основное использование `collect()` это преобразование диапазона `(Range)` в массив `(Vector)`.

В Julia диапазон `(1:5)` — это ленивый объект, который хранит только начальное и конечное значение, но не создает массив.
Если вам нужен массив значений диапазона, используйте `collect()`:

In [6]:
r = 1:5       # Диапазон от 1 до 5
v = collect(r)  # Преобразование в массив (вектор)


5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [7]:
k = collect(1:3)   # Вектор из диапазона от 1 до 3

3-element Vector{Int64}:
 1
 2
 3

#### **🔹 Определение вектора из чисел с плавающей запятой.**


Для примера создадим вектор с длинной `3` и заполненный `1.55` - числами с плавающей точкой (тип Float64):

In [8]:
y = fill(1.55, 3) # вектор x длины 3, заполненный 1.55 - числами с плавающей точкой

3-element Vector{Float64}:
 1.55
 1.55
 1.55

#### **🔹 Подведём итог по полученным типам данных в Julia.**  

В Julia **векторы и матрицы** представляют собой **разные структуры данных**, имеющие разные размеры и типы:  

- **Матрица** `A` имеет тип **`Matrix{Int64}`** (`Array{Int64,2}`) – это **двумерный массив**.  
  
- **Вектор** `x` имеет тип **`Vector{Int64}`** (`Array{Int64,1}`) – это **одномерный массив** с целыми числами. 
   
- **Вектор** `y` имеет тип **`Vector{Float64}`** (`Array{Float64,1}`) – это **одномерный массив** с числами с плавающей запятой.  

<br>

##### **📌 Важные псевдонимы в Julia.**

Для удобства в Julia используются **псевдонимы типов массивов**: 

- **`Vector{Type} ≡ Array{Type,1}`** → одномерный массив (вектор).
    
- **`Matrix{Type} ≡ Array{Type,2}`** → двумерный массив (матрица).  

Это делает код **более читаемым и удобным**, особенно при работе с линейной алгеброй.  

<br>

##### **📌 Основные выводы:**

✅ Векторы (`Vector{T}`) – **одномерные** массивы, матрицы (`Matrix{T}`) – **двумерные**.

✅ **Операции с матрицами и векторами** в Julia работают **так же, как в других языках**, но более **оптимизированы**. 

✅ **Julia автоматически выбирает подходящий тип данных**, обеспечивая **высокую производительность**.  



<br>

---

<br>

### **2️⃣ Стандартные матричные операции в Julia.**

<br>

### **🔹 1. Умножение (Multiplication)**  
Julia поддерживает стандартные **матричные операции**, такие как умножение матрицы на вектор.  

In [9]:
b = A * x

3-element Vector{Int64}:
 12
 16
 14

📌 Оператор `*` используется для **матричного умножения** (`A` на `x`).  

🔹 **Результат** будет вектором `Vector{Float64}`, так как `A` — целочисленная (`Int64`), а `x` содержит числа с плавающей запятой (`Float64`).

<br>

### **🔹 2. Транспонирование и сопряженное транспонирование (адъюнгирование) матрицы**  

В Julia, как и в математике, различают два вида транспонирования:  

1. **Обычное транспонирование** – перестановка строк и столбцов.  
   
2. **Сопряженное транспонирование (адъюнгирование)** – транспонирование с одновременным комплексным сопряжением элементов.  


#####  Транспонирование — это операция в линейной алгебре, при которой строки матрицы преобразуются в столбцы, и наоборот. Результатом транспонирования матрицы $ A $ является новая матрица $ A^T $ (или $ A'$), где строки исходной матрицы становятся столбцами, а столбцы — строками.

<br>

### Пример:

Рассмотрим матрицу $ A $ размером $ 2 \times 3 $:

$$ A = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix} $$

Транспонированная матрица $ A^T $ будет иметь размер $ 3 \times 2 $:

$$ A^T = \begin{pmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{pmatrix} $$

### Свойства транспонирования:

1. **Двойное транспонирование**: Транспонирование транспонированной матрицы возвращает исходную матрицу:
   $ (A^T)^T = A $

2. **Сумма матриц**: Транспонирование суммы матриц равно сумме транспонированных матриц:
   $ (A + B)^T = A^T + B^T $

3. **Произведение матриц**: Транспонирование произведения матриц равно произведению транспонированных матриц в обратном порядке:
   $ (AB)^T = B^T A^T $

4. **Скалярное произведение**: Транспонирование произведения матрицы на скаляр равно произведению транспонированной матрицы на тот же скаляр:
   $ (cA)^T = cA^T $

Транспонирование широко используется в различных областях математики, физики, инженерии и компьютерных наук для упрощения вычислений и решения задач, связанных с матрицами.

<br>

#### **2.1 Обычное транспонирование**

Обычное транспонирование просто меняет строки и столбцы местами.

**Например:**

Создадим матрицу `А`:

```julia
A = [1 2 3; 
     4 5 6; 
     7 8 9]  # Задаем матрицу A (3×3)
```

In [10]:
A = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Теперь её транспонируем:

In [11]:
transpose(A)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

🔹 **Результат**:

Строки и столбцы поменялись местами

```julia
3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9
 
```
📌 **Обычное транспонирование используется для любых матриц и не затрагивает значения элементов.**  

<br>

#### **2.2 Сопряженное транспонирование (адъюнгирование)**  

Если матрица содержит **комплексные числа**, то операция `A'` выполняет **сопряженное транспонирование**.

Наша матрица `А` с комплексными числами:

In [12]:
A = [1+2im 3-im; 4 5+3im]

2×2 Matrix{Complex{Int64}}:
 1+2im  3-1im
 4+0im  5+3im

### **🔹 2.
Теперь выполним сопряженное транспонирование:

In [13]:
A'

2×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 1-2im  4+0im
 3+1im  5-3im

🔹 **Результат**:
 
```julia
2×2 Matrix{Complex{Int64}}:
 1 - 2im   4
 3 + 1im   5 - 3im
 
```
📌 **Что мы видим?** 

- Что матрица **Транспонируется** , т.е. поменялись местами строки и столбцы.  
  
- Что произошло **Комплексное сопряжение**, т.е. у элементов матрицы `А` изменился знак мнимой части \( i \) на противоположный.  


👉 **Если матрица содержит только вещественные числа, `A'` работает так же, как `transpose(A)`.**  


<br>

#### **🔹 3. Транспонированное умножение**  

В Julia можно записывать **умножение транспонированной матрицы на саму себя** без оператора `*` как `A'A`:  



In [14]:
A = [1 2 3; 4 5 6; 7 8 9] # задаем матрицу А

A'A # умножаем матрицу на транспонированную матрицу

3×3 Matrix{Int64}:
 66   78   90
 78   93  108
 90  108  126

Запись `A'A` означает `adjoint(A) * A`, то есть **сопряжённое** транспонирование,
умноженное на `A`.

Для **вещественной** матрицы сопряжение ничего не меняет, поэтому здесь
`A'A` и `transpose(A) * A` дают один и тот же результат — проверим:

In [15]:
A = [1 2 3; 4 5 6; 7 8 9]

transpose(A) * A

3×3 Matrix{Int64}:
 66   78   90
 78   93  108
 90  108  126

> ⚠️ **Но это совпадение верно только для вещественных матриц.**
> `A'` — это `adjoint`, а не `transpose`. Как только в матрице появляются
> комплексные числа, результаты расходятся:

In [16]:
Ac = [1+2im  3-1im
      4+0im  5+3im]

println("Ac'Ac              = "); display(Ac'Ac)
println("transpose(Ac) * Ac = "); display(transpose(Ac) * Ac)

@show Ac'Ac == transpose(Ac) * Ac    # false — это разные операции

Ac'Ac              = 


2×2 Matrix{Complex{Int64}}:
 21+0im  21+5im
 21-5im  44+0im

transpose(Ac) * Ac = 


2×2 Matrix{Complex{Int64}}:
 13+4im   25+17im
 25+17im  24+24im

Ac' * Ac == transpose(Ac) * Ac = false

false

Разница не косметическая. Матрица $A^{*}A$ всегда **эрмитова** и
неотрицательно определена — именно на этом строятся метод наименьших квадратов
и разложение Холецкого (занятие 13). У матрицы $A^{\mathsf{T}}A$ для комплексного
$A$ таких свойств нет.

Подробное объяснение различия — в занятии 11.

In [17]:
using LinearAlgebra

@show ishermitian(Ac'Ac)                 # true
@show ishermitian(transpose(Ac) * Ac)    # false

ishermitian(Ac' * Ac) = true
ishermitian(transpose(Ac) * Ac) = false


false

📌 **Это используется в линейной алгебре**, например, для вычисления **граммианов** и **норм уравнений в методе наименьших квадратов**.  

<br>

---

<br>

### **3️⃣ Решение линейных систем (Solving Linear Systems)**  

<br>

Оператор **обратного деления `\`** - решает линейные уравнения вида **$Ax = b$**. В зависимости от формы матрицы $ A $ **Julia** автоматически выбирает подходящий метод решения.
<br>

#### **⬜ 1. Квадратная система (Square System)**  

Если \( A \) – **квадратная матрица** (число строк = числу столбцов), оператор `\` находит **точное решение**:  

In [18]:
A = rand(3, 3)
b = rand(3)

x = A \ b  # Решает Ax = b

3-element Vector{Float64}:
 -4.854944827110179
  0.19654716736679093
  3.1336633829626135

📌 **Если матрица невырождена**, Julia использует метод **LU-разложения** для быстрого решения.

<br>

#### **⬜ 2. Переопределенная система (Overdetermined, "высокая" матрица)**  

Если уравнение имеет **больше уравнений, чем переменных** (**"высокая" матрица**), Julia находит **наилучшее среднеквадратичное решение** (метод наименьших квадратов):  


In [19]:
Atall = rand(3, 2)  # 3 строки, 2 столбца (больше уравнений, чем переменных)
b = rand(3)

x = Atall \ b  # Решает Ax = b

2-element Vector{Float64}:
  0.6591016462977555
 -0.3128615774059634

📌 **Julia автоматически использует метод QR-разложения**.

<br>

#### **⬜ 3. Недоопределенная система (Underdetermined, "короткая" матрица)**  

Если уравнение имеет **меньше уравнений, чем переменных** (**"короткая" матрица**), Julia вычисляет **минимальное нормированное решение**:


In [20]:
Ashort = rand(2, 3)  # 2 строки, 3 столбца (меньше уравнений, чем переменных)
bshort = rand(2)

x = Ashort \ bshort  # Решает Ax = b

3-element Vector{Float64}:
 0.052794067612497345
 0.02429063072759197
 0.565625635133797

📌 Для недоопределённой системы с полным строчным рангом `\` возвращает решение
**минимальной нормы** — из бесконечного множества решений выбирается самое короткое.

> Технически Julia использует не SVD, а LQ/QR-разложение: оно дешевле и даёт тот же
> ответ. Ниже мы убедимся, что результат совпадает с `pinv(A) * b`.

<br>

#### **⬜ 4. Неполный ранг (Rank-Deficient System)**  

Если \( A \) содержит **зависимые столбцы** (линейно зависимые строки), то Julia решает уравнение с **минимальной нормой**:  

In [21]:
v = rand(3)
rankdef = hcat(v, v)  # Создаем матрицу с зависимыми столбцами

x = rankdef \ b  # Найдет минимальное нормированное решение

2-element Vector{Float64}:
 0.23180800889802827
 0.23180800889802827

### 🔬 Проверим утверждения, а не поверим им на слово

In [22]:
using LinearAlgebra

# Недоопределённая система: решение действительно минимальной нормы
Au = rand(2, 3); bu = rand(2)
x_backslash = Au \ bu
x_pinv      = pinv(Au) * bu

@show norm(x_backslash)
@show norm(x_pinv)
@show x_backslash ≈ x_pinv        # true: \ даёт решение минимальной нормы

norm(x_backslash) = 2.2085061364357146


norm(x_pinv) = 2.2085061364357137
x_backslash ≈ x_pinv = true

true

In [23]:
# Оба вектора решают систему одинаково точно —
# различаться могло бы только то, какое из решений выбрано.
@show norm(Au * x_backslash - bu)
@show norm(Au * x_pinv - bu)

norm(Au * x_backslash - bu) = 0.0
norm(Au * x_pinv - bu) = 3.1401849173675503e-16


3.1401849173675503e-16

📌 При неполном ранге задача не имеет единственного решения, и `\` возвращает
одно из наименее-квадратичных решений.

> ⚠️ Не полагайтесь на то, *какое именно* решение вы получите: для матриц
> неполного ранга это деталь реализации, а не гарантия языка. Если вам нужно
> именно решение минимальной нормы — вычисляйте его явно через `pinv(A) * b`
> и указывайте это в коде.

#### **😺 Важно запомнить:** 

✅ **`transpose(A)`** – обычное транспонирование.

✅ **`A'`** – транспонирование + комплексное сопряжение. 

✅ **`A'A`** – транспонированное умножение.

✅ **`A \ b`** – оператор решения линейных систем, автоматически выбирает оптимальный метод.  

**💡 Julia делает линейную алгебру интуитивной и мощной, автоматизируя сложные вычисления!** 🚀

<br>

---

<br>

### **4️⃣  Библиотека `LinearAlgebra` в Julia.**

Хотя **основные функции линейной алгебры** доступны в Julia **по умолчанию**, стандартная библиотека **`LinearAlgebra`** предоставляет **дополнительные инструменты** для работы с матрицами и векторами.  

📌 **Что добавляет `LinearAlgebra`?**  
- **Факторизации** (LU, QR, Cholesky, SVD и др.).  
- **Структурированные матрицы** (диагональные, разреженные, симметричные и др.).  
- **Вычисления норм, определителей, ранга, следа и др.**  
- **Операции с векторами** (скалярное, векторное, смешанное произведение).  

📌 **Как подключить библиотеку?**  

In [24]:
using LinearAlgebra  # Подключаем библиотеку LinearAlgebra

После этого **новые функции** становятся доступными в текущем сеансе. 

<br>

### **🔹 Основные возможности `LinearAlgebra`**

##### ✅ **1. Нормы и ортогональность**  
Функция `norm()` вычисляет **разные нормы** векторов и матриц:  

In [25]:
using LinearAlgebra

x = [3, 4]
println(norm(x))       # Евклидова норма (по умолчанию)
println(norm(x, 1))    # 1-норма (сумма модулей элементов)
println(norm(x, Inf))  # Бесконечная норма (максимальный элемент)

5.0


7.0
4.0


##### ✅ **2. Определитель матрицы**  

In [26]:
A = [1 2; 3 4]
det(A)  # -2.0

-2.0

##### ✅ **3. Ранг и след матрицы**  

In [27]:
rank(A)   # 2 (ранг матрицы)
tr(A)     # 5 (след матрицы, сумма диагональных элементов)

5

##### ✅ **4. Факторизации (разложения матриц)**  

In [28]:
A = [4 3; 6 3]
F = lu(A)    # LU-разложение
println(F.L) # Нижняя треугольная матрица
println(F.U) # Верхняя треугольная матрица

[1.0 0.0; 0.6666666666666666 1.0]
[6.0 3.0; 0.0 1.0]


Также доступны `qr(A)`, `svd(A)`, `cholesky(A)`, `eigen(A)`.

##### ✅ **5. Работа с особыми матрицами**  

In [29]:
D = Diagonal([1, 2, 3])   # диагональная матрица: хранится только диагональ

# ⚠️ Symmetric НЕ проверяет, симметрична ли матрица!
Ans = [1 2
       3 4]              # заведомо НЕ симметрична
@show issymmetric(Ans)   # false

S = Symmetric(Ans)       # берётся верхний треугольник, нижний ИГНОРИРУЕТСЯ
@show Matrix(S)          # [1 2; 2 4] — элемент 3 бесследно исчез

issymmetric(Ans) = false
Matrix(S) = 

[1 2; 2 4]


2×2 Matrix{Int64}:
 1  2
 2  4

> ⚠️ **Это важная деталь.** `Symmetric(A)` — не проверка и не преобразование,
> а **обещание**, которое вы даёте компилятору: «считай эту матрицу симметричной».
> Julia поверит вам на слово и будет читать только один треугольник.
>
> Если обещание неверно, ошибки не будет — будут молча неверные результаты.
> Поэтому `Symmetric`, `Hermitian`, `UpperTriangular` и подобные обёртки применяют
> к матрицам, симметричность которых известна **из постановки задачи**.

Выигрыш от такого обещания — реальный: алгоритм для симметричных матриц
и быстрее, и точнее.

In [30]:
Asym = [4.0 1.0; 1.0 3.0]      # действительно симметрична
@show issymmetric(Asym)

@show eigvals(Asym)                  # общий алгоритм
@show eigvals(Symmetric(Asym))       # специализированный: гарантирует вещественность

issymmetric(Asym) = true
eigvals(Asym) = 

[2.381966011250105, 4.618033988749895]
eigvals(Symmetric(Asym)) = [2.381966011250105, 4.618033988749895]

2-element Vector{Float64}:
 2.381966011250105
 4.618033988749895

##### ✅ **6. Скалярное и векторное произведение**

Эти две функции понадобятся в упражнениях.

In [31]:
u = [1, 2, 3]
w = [4, 5, 6]

@show dot(u, w)      # скалярное произведение → число
@show u ⋅ w          # то же самое: \cdot<Tab>
@show cross(u, w)    # векторное произведение → вектор (только для длины 3)
@show u × w          # то же самое: \times<Tab>

dot(u, w) = 32
u ⋅ w = 32
cross(u, w) = [-3, 6, -3]


u × w = [-3, 6, -3]


3-element Vector{Int64}:
 -3
  6
 -3

**Внешнее (диадное) произведение** — это, наоборот, матрица. Получается умножением
вектора-столбца на вектор-строку:

In [32]:
outer = u * u'       # (3×1) * (1×3) → матрица 3×3
display(outer)
@show size(u), size(u'), size(outer)
@show rank(outer)    # 1 — внешнее произведение всегда даёт матрицу ранга 1

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

(size(u), size(u'), size(outer)) = ((3,), (1, 3), (3, 3))


rank(outer) = 1


1

> 📌 Обратите внимание на размерности: `u` имеет размер `(3,)`, а `u'` — `(1, 3)`.
> В Julia вектор — это **не** матрица-столбец, но `u'` превращает его в строку.
> Поэтому `u' * u` даёт число, а `u * u'` — матрицу 3×3. Порядок решает всё.

##### ✅ **7. Единичный оператор `I`**

In [33]:
@show I                      # UniformScaling — «единица» без фиксированного размера
@show Matrix(I, 3, 3)        # настоящая единичная матрица 3×3, если она нужна

Q = [4.0 1.0; 1.0 3.0]
@show Q * I == Q             # I подстраивается под размер
@show Q + 2I                 # прибавить 2 к диагонали — частый приём

I = UniformScaling{Bool}(true)
Matrix(I, 3, 3) = 

Bool[1 0 0; 0 1 0; 0 0 1]
Q * I == Q = true


Q + 2I = 

[6.0 1.0; 1.0 5.0]


2×2 Matrix{Float64}:
 6.0  1.0
 1.0  5.0

`I` не хранит нулей и не выделяет память, поэтому `A + 2I` дешевле, чем
`A + 2 * Matrix(I, n, n)`.

##### ✅ **8. Что происходит под капотом: BLAS и LAPACK**

Операции `*`, `\`, `lu`, `qr`, `eigen` не реализованы на Julia «в лоб».
Они вызывают **BLAS** и **LAPACK** — библиотеки, которые десятилетиями
оптимизировались под конкретные процессоры.

In [34]:
@show BLAS.get_config().loaded_libs      # какая реализация BLAS используется
@show BLAS.get_num_threads()             # во сколько потоков считает BLAS

(BLAS.get_config()).loaded_libs = LinearAlgebra.BLAS.LBTLibraryInfo[LBTLibraryInfo(libopenblas64_.so, ilp64)]


BLAS.get_num_threads() = 2


2

Практический вывод: **не пишите свой цикл умножения матриц**. Встроенный `*`
почти наверняка окажется быстрее, потому что за ним стоит многолетняя
оптимизация под кэш и векторные инструкции процессора. Подробнее о том,
почему это так, — в занятии 10.

##### **🔹 Подводим итог по `LinearAlgebra`:**

✅ **`LinearAlgebra` расширяет стандартные функции Julia для работы с матрицами и векторами**.

✅ Включает **факторизации, вычисление норм, работу с особыми матрицами**.  

✅ Подключается командой **`using LinearAlgebra`**.  

**💡 Важно!** 

**Если вы работаете с линейной алгеброй в Julia, то этот пакет для вас - незаменимый инструмент!**

<br>

---

<br>

<br>

---

<br>

## Упражнения 🚀

Решение пишите в ячейке `# Ваше решение`, затем запускайте ячейку проверки.
`@assert` молчит при успехе — если ничего не выведено, задание засчитано.

<br>

#### ✅ Задание 12.1 — Скалярное произведение

Вычислите скалярное произведение вектора `v` на самого себя и присвойте
результат переменной `dot_v`.

In [35]:
using LinearAlgebra
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [36]:
# Ваше решение

In [37]:
# Правильное решение

# dot(v, v) — это сумма квадратов координат: 1² + 2² + 3² = 14.
dot_v = dot(v, v)

@show dot_v
@show v ⋅ v            # эквивалентная запись
@show sum(v .^ 2)      # то же самое «вручную» — видно, что именно считается
@show norm(v)^2        # и связь с нормой: ‖v‖² = v⋅v

dot_v = 14
v ⋅ v = 14
sum(v .^ 2) = 14


norm(v) ^ 2 = 14.0


14.0

In [38]:
@assert dot_v == 14
println("✔ Задание 12.1 выполнено")

✔ Задание 12.1 выполнено


<br>

#### ✅ Задание 12.2 — Внешнее произведение

Вычислите внешнее произведение вектора `v` на самого себя
и присвойте результат переменной `outer_v`.

Следите за порядком множителей: он определяет, получите вы число или матрицу.

In [39]:
# Ваше решение

In [40]:
# Правильное решение

# v — столбец (3,), v' — строка (1,3).
# Столбец * строка → матрица 3×3 (внешнее произведение).
# Строка * столбец → число (скалярное произведение).
outer_v = v * v'

display(outer_v)
@show size(v), size(v'), size(outer_v)
@show rank(outer_v)      # 1: все строки пропорциональны v

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

(size(v), size(v'), size(outer_v)) = ((3,), (1, 3), (3, 3))
rank(outer_v) = 1


1

In [41]:
@assert outer_v == [1 2 3
                    2 4 6
                    3 6 9]
@assert rank(outer_v) == 1
println("✔ Задание 12.2 выполнено")

✔ Задание 12.2 выполнено


<br>

#### ✅ Задание 12.3 — Векторное произведение

Вычислите векторное произведение вектора `v` на самого себя и присвойте
результат переменной `cross_v`.

Прежде чем считать, попробуйте предсказать ответ: что геометрически означает
векторное произведение вектора на самого себя?

Документация: [`LinearAlgebra.cross`](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.cross)

In [42]:
# Ваше решение

In [43]:
# Правильное решение

# Векторное произведение даёт вектор, перпендикулярный обоим сомножителям,
# а его длина равна площади параллелограмма, построенного на них.
# Вектор с самим собой параллелограмма не образует — площадь нулевая,
# поэтому результат всегда нулевой вектор.
cross_v = cross(v, v)

@show cross_v
@show v × v                    # эквивалентная запись
@show cross(v, 2v)             # для любых коллинеарных векторов тоже ноль

cross_v = [0, 0, 0]
v × v = [0, 0, 0]
cross(v, 2v) = [0, 0, 0]

3-element Vector{Int64}:
 0
 0
 0

In [44]:
@assert cross_v == [0, 0, 0]
println("✔ Задание 12.3 выполнено")

✔ Задание 12.3 выполнено


<br>

#### ✅ Задание 12.4 — Решение системы и невязка

Решите систему $Ax = b$ и запишите:

- решение в `x_sol`;
- норму невязки $\|Ax - b\|$ в `resid`.

Используйте оператор, который для этого предназначен, — не обратную матрицу.

In [45]:
A = [ 3.0  1.0  -1.0
      2.0 -2.0   4.0
     -1.0  0.5  -1.0 ]
b = [4.0, 2.0, -1.0]

3-element Vector{Float64}:
  4.0
  2.0
 -1.0

In [46]:
# Ваше решение

In [47]:
# Правильное решение

# Оператор \ решает систему напрямую: для квадратной невырожденной матрицы
# внутри используется LU-разложение с частичным выбором главного элемента.
x_sol = A \ b

# Невязка показывает, насколько точно найденный x удовлетворяет системе.
resid = norm(A * x_sol - b)

@show x_sol
@show resid
@show A * x_sol ≈ b

x_sol = [1.0000000000000007, 1.9999999999999962, 0.999999999999998]
resid = 9.930136612989092e-16
A * x_sol ≈ b = true


true

In [48]:
@assert x_sol ≈ [1.0, 2.0, 1.0]
@assert resid < 1e-10
println("✔ Задание 12.4 выполнено")

✔ Задание 12.4 выполнено


<br>

#### ✅ Задание 12.5 — Прикладная задача: метод наименьших квадратов

Есть измерения: при значениях `t` получены значения `y`. Данные зашумлены,
поэтому точная прямая через все точки не проходит.

Найдите прямую $y = a + b\,t$, наилучшую в смысле наименьших квадратов.

1. Постройте матрицу плана `X`, у которой первый столбец — единицы, второй — `t`.
2. Решите переопределённую систему и запишите коэффициенты в `coef`
   (`coef[1]` — свободный член $a$, `coef[2]` — наклон $b$).
3. Запишите в `rms` среднеквадратичную ошибку приближения.

Подсказка: оператор `\` умеет решать переопределённые системы сам —
именно это он делает через QR-разложение.

In [49]:
t = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
y = [1.02, 2.95, 5.10, 6.90, 9.05, 11.01]   # примерно y = 1 + 2t с шумом

6-element Vector{Float64}:
  1.02
  2.95
  5.1
  6.9
  9.05
 11.01

In [50]:
# Ваше решение

In [51]:
# Правильное решение

# Модель: y ≈ a·1 + b·t. Записываем её как систему X * [a, b] ≈ y.
# Уравнений (6) больше, чем неизвестных (2), — система переопределена.
X = [ones(length(t)) t]        # матрица плана 6×2

# \ для переопределённой системы возвращает решение наименьших квадратов (через QR).
coef = X \ y

resid_vec = X * coef - y
rms = norm(resid_vec) / sqrt(length(y))

println("a (свободный член) = ", coef[1])
println("b (наклон)         = ", coef[2])
println("RMS-ошибка         = ", rms)

a (свободный член) = 1.0014285714285718


b (наклон)         = 2.0014285714285713
RMS-ошибка         = 0.06495419631592428


**Почему не нормальные уравнения?**

В учебниках метод наименьших квадратов часто записывают как
$\hat\beta = (X^{\mathsf{T}}X)^{-1}X^{\mathsf{T}}y$. Формула верна, но для
вычислений плоха: возведение в квадрат **удваивает** число обусловленности
задачи, а затем ещё и обращается матрица.

`X \ y` решает ту же задачу через QR-разложение — точнее и без явного обращения.
Сравним оба пути:

In [52]:
coef_qr     = X \ y                       # ✅ рекомендуемый способ
coef_normal = (X' * X) \ (X' * y)         # нормальные уравнения (без inv — уже лучше)
coef_worst  = inv(X' * X) * X' * y        # ❌ буквально по учебной формуле

@show coef_qr
@show coef_normal
@show coef_worst
@show cond(X)          # обусловленность исходной задачи
@show cond(X' * X)     # ≈ cond(X)² — вот цена нормальных уравнений

coef_qr = [1.0014285714285718, 2.0014285714285713]


coef_normal = [1.0014285714285716, 2.0014285714285713]
coef_worst = [1.0014285714285691, 2.001428571428571]
cond(X) = 

5.7799794492230125
cond(X' * X) = 33.40816243344034


33.40816243344034

In [53]:
@assert isapprox(coef[1], 1.0; atol=0.1)   "свободный член должен быть ≈ 1"
@assert isapprox(coef[2], 2.0; atol=0.1)   "наклон должен быть ≈ 2"
@assert rms < 0.1                          "приближение должно быть хорошим"
println("✔ Задание 12.5 выполнено")

✔ Задание 12.5 выполнено


<br>

---

<br>

## 📝 Итоги занятия

| Задача | Как в Julia | Замечание |
|---|---|---|
| Скалярное произведение | `dot(u, w)`, `u ⋅ w` | результат — число |
| Внешнее произведение | `u * u'` | результат — матрица ранга 1 |
| Векторное произведение | `cross(u, w)`, `u × w` | только длина 3 |
| Транспонирование | `transpose(A)` | без сопряжения |
| Сопряжённое транспонирование | `A'` | **по умолчанию берите это** |
| Норма | `norm(x)`, `norm(x, 1)` | удобно для проверки равенств |
| Решение системы | `A \ b` | не `inv(A) * b` |
| Наименьшие квадраты | `X \ y` | не нормальные уравнения |
| Единичный оператор | `I` | не выделяет память |
| Структура матрицы | `Diagonal`, `Symmetric` | **обещание**, а не проверка |

**Что важно унести:**

1. `A'` — это `adjoint`. С вещественными матрицами разницы нет, с комплексными — есть.
2. `\` сам выбирает алгоритм по форме матрицы: LU для квадратных,
   QR для переопределённых, минимальная норма для недоопределённых.
3. Обёртки структуры (`Symmetric`, `Diagonal`) ускоряют вычисления, но Julia
   **верит вам на слово** и не проверяет, правда ли матрица такова.

В **занятии 13** мы перейдём к факторизациям: разберём, что именно `\` делает
внутри, и научимся переиспользовать одно разложение для многих правых частей.

---

[← Одиннадцатое занятие. Понятия линейной алгебры](11%20-%20Linear%20algebra%20concepts.ipynb) | [Оглавление](README.md) | [Тринадцатое занятие. Факторизации матриц →](13%20-%20Factorizations%20and%20other%20fun.ipynb)